export const SUB_MENU_ROUTES: { [key: string]: string } = {
  // 'CC-Cross Functional Reviewer': './master-data-management',
  // 'CC-QA Approver': './sd/quotation-home-page',
  'AD-Administrator': './rqpadminui/admin/ad-administrator',
  'AD-Master Data': './rqpadminui/admin/master-management/ad-master',
  'PIMP-Master Data': './pimp-master-home-page',
  'FM-Master Data': './rmp/fm-master-home-page',
  'CLV-Master Data': './rqpquailtyui/vl/vl-master-home-page',
  'CLV-Initiator': './vl/clv-initiator',
  'CLV-Update': './vl/clv-update-home-page',
  'CLV-Approver': './vl/clv-reviewer-home-page',
  'QT-Initator': './sd/quotation-home-page',
  'QT-Update': './rqpadminui/sd/qt-update-page',
  'QT-Master Data': './rqpquailtyui/sd/qt-master-data-home-page',
  'SQT-Initiator': './rqpadminui/sd/qt-initiator',
  'SQT-Reviewer': './rqpadminui/sd/qt-reviewer',
  'SQT-Approver': './rqpadminui/sd/qt-reviewer',
  'SQT-Update': './rqpadminui/sd/qt-update',
  'SD-Master Data': './rqpquailtyui/sd/qt-master-data-home-page',
  'URS-Initiator': './dms/user-initiator',
  'URS-Department Reviewer': './dms/urs-review-home-page',
  'URS-QA Reviewer': './dms/urs-qa-review-home-page',
  'URS-Cross Functional Reviewer': './dms/urs-cross-function-review-home-page',
  'URS-QA Approver': './dms/urs-qa-approver-review-home-page',
  'URS-Authorization': './dms/urs-authorization-review-home-page',
  'URS-DMS Manager': './dms/urs-closure-review-home-page',
  'URS-Closure': './dms/urs-closure-review-home-page',
  'URS-Update': './dms/urs-update-home-page',
  'STP-Initiator': './dms/stp-initiator',
  'STP-Department Reviewer': './dms/stp-review-home-page',
  'STP-QA Reviewer': './dms/stp-qa-review-home-page',
  'STP-Cross Functional Reviewer': './dms/stp-cross-function-review-home-page',
  'STP-QA Approver': './dms/stp-qa-approver-review-home-page',
  'STP-Training Coordinator': './dms/stp-authorization-review-home-page',
  'STP-DMS Manager': './dms/stp-closure-review-home-page',
  'STP-Update': './dms/stp-update-home-page',
  'STP-PR-Initiator': './dms/stp-pr-initiator-save',
  'STP-PR-Update': './dms/stp-pr-update',
  'STP-PR-Reviewer': './dms/stp-pr-reviewer',
  'STP-PR-Approver': './dms/stp-pr-reviewer',
  'STP-PR-Print': './dms/stp-pr-reviewer',
  'PVP-Initiator': './dms/pvp-initiator',
  'PVP-Department Reviewer': './dms/pvp-review-home-page',
  'PVP-QA Reviewer': './dms/pvp-qa-review-home-page',
  'PVP-Cross Functional Reviewer': './dms/pvp-cross-function-review-home-page',
  'PVP-QA Approver': './dms/pvp-qa-approver-review-home-page',
  'PVP-Training Coordinator': './dms/pvp-authorization-review-home-page',
  'PVP-DMS Manager': './dms/pvp-closure-review-home-page',
  'PVP-Update': './dms/pvp-update-home-page',
  'PVP-PR-Initiator': './dms/pvp-pr-initiator-save',
  'PVP-PR-Update': './dms/pvp-pr-update',
  'PVP-PR-Reviewer': './dms/pvp-pr-reviewer',
  'PVP-PR-Approver': './dms/pvp-pr-reviewer',
  'PVP-PR-Print': './dms/pvp-pr-reviewer',
  'PVR-Initiator': './dms/pvr-initiator',
  'PVR-Department Reviewer': './dms/pvr-review-home-page',
  'PVR-QA Reviewer': './dms/pvr-qa-review-home-page',
  'PVR-Cross Functional Reviewer': './dms/pvr-cross-function-review-home-page',
  'PVR-QA Approver': './dms/pvr-qa-approver-review-home-page',
  'PVR-Training Coordinator': './dms/pvr-authorization-review-home-page',
  'PVR-DMS Manager': './dms/pvr-closure-review-home-page',
  'PVR-Update': './dms/pvr-update-home-page',
  'PVR-PR-Initiator': './dms/pvr-pr-initiator-save',
  'PVR-PR-Update': './dms/pvr-pr-update',
  'PVR-PR-Reviewer': './dms/pvr-pr-reviewer',
  'PVR-PR-Approver': './dms/pvr-pr-reviewer',
  'PVR-PR-Print': './dms/pvr-pr-reviewer',
  'SOP-Initiator': './rqpquailtyui/dms/sop-initiator',
  'SOP-Update': './rqpquailtyui/dms/sop-update-home-page',
  'SOP-Department Reviewer': './rqpquailtyui/dms/sop-review-home-page',
  'SOP-QA Reviewer': './rqpquailtyui/dms/sop-qa-review-home-page',
  'SOP-Cross Functional Reviewer':
    './rqpquailtyui/dms/sop-cross-function-review-home-page',
  'SOP-QA Approver': './rqpquailtyui/dms/sop-qa-approver-review-home-page',
  'SOP-Authorization': './rqpquailtyui/dms/sop-authorization-review-home-page',
  'SOP-Training Coordinator':
    './rqpquailtyui/dms/sop-training-review-home-page',
  'SOP-Documentation': './dms/sop-documentation-review-home-page',
  'SOP-DMS Manager': './rqpquailtyui/dms/sop-documentation-review-home-page',
  'SOP-User': './rqpquailtyui/dms/sop-user-home-page',
  'SOP-PR-Initiator': '/dms/sop-pr-initiator-save',
  'SOP-PR-Update': '/dms/sop-pr-update',
  'SOP-PR-Reviewer': '/dms/sop-pr-reviewer',
  'SOP-PR-Approver': '/dms/sop-pr-reviewer',
  'SOP-PR-Print': '/dms/sop-pr-reviewer',
  'SOPADPR-Initiator': '/dms/sop-ad-pr-initiator-save',
  'SOPADPR-Update': '/dms/sop-ad-pr-update',
  'SOPADPR-Reviewer': '/dms/sop-ad-pr-reviewer',
  'SOPADPR-Approver': '/dms/sop-ad-pr-reviewer',
  'SOPADPR-Print': '/dms/sop-ad-pr-reviewer',
  'SPC-Initiator': './dms/spc-initiator',
  'SPC-Department Reviewer': './dms/spc-review-home-page',
  'SPC-QA Reviewer': './dms/spc-qa-review-home-page',
  'SPC-Cross Functional Reviewer': './dms/spc-cross-function-review-home-page',
  'SPC-QA Approver': './dms/spc-qa-approver-review-home-page',
  'SPC-Training Coordinator': './dms/spc-authorization-review-home-page',
  'SPC-Documentation': './dms/spc-closure-review-home-page',
  'SPC-Update': './dms/spc-update-home-page',
  'SPC-PR-Initiator': './dms/spc-pr-initiator-save',
  'SPC-PR-Update': './dms/spc-pr-update',
  'SPC-PR-Reviewer': './dms/spc-pr-reviewer',
  'SPC-PR-Approver': './dms/spc-pr-reviewer',
  'SPC-PR-Print': './dms/spc-pr-reviewer',
  'AWS-Initiator': './dms/aws-initiator',
  'AWS-Department Reviewer': './dms/aws-review-home-page',
  'AWS-QA Reviewer': './dms/aws-qa-review-home-page',
  'AWS-Cross Functional Reviewer': './dms/aws-cross-function-review-home-page',
  'AWS-QA Approver': './dms/aws-qa-approver-review-home-page',
  'AWS-Training Coordinator': './dms/aws-review-home-page',
  'AWS-DMS Manager': './dms/aws-review-home-page',
  'AWS-Authorization': './dms/aws-authorization-review-home-page',
  'AWS-Closure': './dms/aws-closure-review-home-page',
  'AWS-Update': './dms/aws-update-home-page',
  'AWS-PR-Initiator': './dms/aws-pr-init-save',
  'AWS-PR-Update': './dms/aws-pr-update',
  'AWS-PR-Reviewer': './dms/aws-pr-reviewer',
  'AWS-PR-Approver': './dms/aws-pr-reviewer',
  'BMR-Initiator': './rqpquailtyui/dms/bmr-initiator',
  'BMR-Department Reviewer': './dms/bmr-review-home-page',
  'BMR-QA Reviewer': './dms/bmr-qa-review-home-page',
  'BMR-Cross Functional Reviewer': './dms/bmr-cross-function-review-home-page',
  'BMR-QA Approver': './dms/bmr-qa-approver-review-home-page',
  'BMR-Training Coordinator': './dms/bmr-authorization-review-home-page',
  'BMR-DMS Manager': './dms/bmr-closure-review-home-page',
  'BMR-Update': './dms/bmr-update-home-page',
  'BMR-PR-Initiator': './dms/bmr-pr-init-save',
  'BMR-PR-Update': './dms/bmr-pr-update',
  'BMR-PR-Reviewer': './dms/bmr-pr-reviewer',
  'BMR-PR-Approver': './dms/bmr-pr-reviewer',
  'BMR-PR-Print': './dms/bmr-pr-reviewer',
  'BPR-Initiator': './rqpquailtyui/dms/bpr-initiator',
  'BPR-Department Reviewer': './rqpquailtyui/dms/bpr-review-home-page',
  'BPR-QA Reviewer': './rqpquailtyui/dms/bpr-qa-review-home-page',
  'BPR-Cross Functional Reviewer':
    './rqpquailtyui/dms/bpr-cross-function-review-home-page',
  'BPR-QA Approver': './rqpquailtyui/dms/bpr-qa-approver-review-home-page',
  'BPR-Training Coordinator':
    './rqpquailtyui/dms/bpr-authorization-review-home-page',
  'BPR-DMS Manager': './rqpquailtyui/dms/bpr-closure-review-home-page',
  'BPR-Update': './rqpquailtyui/dms/bpr-update-home-page',
  'BPR-PR-Initiator': './dms/bpr-pr-init-save',
  'BPR-PR-Update': './dms/bpr-pr-update',
  'BPR-PR-Reviewer': './dms/bpr-pr-reviewer',
  'BPR-PR-Approver': './dms/bpr-pr-reviewer',
  'BPR-PR-Print': './dms/bpr-pr-reviewer',
  'COA-Initiator': './dms/coa-initiator',
  'COA-Department Reviewer': './dms/coa-review-home-page',
  'COA-QA Reviewer': './dms/coa-qa-review-home-page',
  'COA-Cross Functional Reviewer': './dms/coa-cross-function-review-home-page',
  'COA-QA Approver': './dms/coa-qa-approver-review-home-page',
  'COA-Training Coordinator': './dms/coa-authorization-review-home-page',
  'COA-DMS Manager': './dms/coa-closure-review-home-page',
  'COA-Update': './dms/coa-update-home-page',
  'COA-PR-Initiator': './dms/coa-pr-init-save',
  'COA-PR-Update': './dms/coa-pr-update',
  'COA-PR-Reviewer': './dms/coa-pr-reviewer',
  'COA-PR-Approver': './dms/coa-pr-reviewer',
  'COA-PR-Print': './dms/coa-pr-reviewer',
  'CVP-Initiator': './dms/cvp-initiator',
  'CVP-Department Reviewer': './dms/cvp-review-home-page',
  'CVP-QA Reviewer': './dms/cvp-qa-review-home-page',
  'CVP-Cross Functional Reviewer': './dms/cvp-cross-function-review-home-page',
  'CVP-QA Approver': './dms/cvp-qa-approver-review-home-page',
  'CVP-DMS Manager': './dms/cvp-closure-review-home-page',
  'CVP-Authorization': './dms/cvp-authorization-review-home-page',
  'CVP-Closure': './dms/cvp-closure-review-home-page',
  'CVP-Update': './dms/cvp-update-home-page',
  'CVP-PR-Initiator': './dms/cvp-pr-init-save',
  'CVP-PR-Update': './dms/cvp-pr-update',
  'CVP-PR-Reviewer': './dms/cvp-pr-reviewer',
  'CVP-PR-Approver': './dms/cvp-pr-reviewer',
  'CVP-PR-Print': './dms/cvp-pr-reviewer',
  'CVR-Initiator': './dms/cvr-initiator',
  'CVR-Department Reviewer': './dms/cvr-review-home-page',
  'CVR-QA Reviewer': './dms/cvr-qa-review-home-page',
  'CVR-Cross Functional Reviewer': './dms/cvr-cross-function-review-home-page',
  'CVR-QA Approver': './dms/cvr-qa-approver-review-home-page',
  'CVR-Training Coordinator': './dms/cvr-authorization-review-home-page',
  'CVR-DMS Manager': './dms/cvr-closure-review-home-page',
  'CVR-Update': './dms/cvr-update-home-page',
  'CVR-PR-Initiator': './dms/cvr-pr-initiator-save',
  'CVR-PR-Update': './dms/cvr-pr-update',
  'CVR-PR-Reviewer': './dms/cvr-pr-reviewer',
  'CVR-PR-Approver': './dms/cvr-pr-reviewer',
  'CVR-PR-Print': './dms/cvr-pr-reviewer',
  'DQ-Initator': './rqpadminui/sd/draft-initator-home-page',
  'DQ-Reviewer': './sd/draft-reviewer-home-page',
  'DQ-Update': './sd/draft-update-home-page',
  'FQ-Initator': './sd/fair-initator-home-page',
  'FQ-Reviewer': './sd/fair-reviewer-home-page',
  'LMS-Master Data': './rqpquailtyui/lms/lms-master-home-page',
  'LMS-User': './rqpquailtyui/lms/lms-user-home-page',
  'QMS-Master Data': './rqpquailtyui/qms/qms-master-home-page',
  'HR-Master Data': './rqpadminui/hr/hr-master-home-page',
  'FI-Master Data': './rqpadminui/fi/fi-master-home-page',
  'LIMS-CM-Master Data': './lims-cm/lims-cm-master-home-page',
  'LIMS-Master Data': './lims/lims-master-home-page',
  'CAPA-Initiator': './rqpquailtyui/qms/capa-initiator',
  'CAPA-Update': './rqpquailtyui/qms/capa-update-home-page',
  'CAPA-Department Reviewer': './rqpquailtyui/qms/capa-reviewer-home-page',
  'CAPA-QA Reviewer': './rqpquailtyui/qms/capa-reviewer-home-page',
  'CAPA-Cross Functional Reviewer':
    './rqpquailtyui/qms/capa-reviewer-home-page',
  'CAPA-QA Approver': './rqpquailtyui/qms/capa-reviewer-home-page',
  'CAPA-Approver': './rqpquailtyui/qms/capa-reviewer-home-page',
  'DEV-Initiator': './rqpquailtyui/qms/dev-initiator',
  'DEV-Update': './rqpquailtyui/qms/dev-update-home-page',
  'DEV-Department Reviewer': './rqpquailtyui/qms/dev-reviewer-home-page',
  'DEV-Reviewer': './rqpquailtyui/qms/dev-reviewer-home-page',
  'DEV-Cross Functional Reviewer': './rqpquailtyui/qms/dev-reviewer-home-page',
  'DEV-Approver': './rqpquailtyui/qms/dev-reviewer-home-page',
  'DEV-Authorization': './rqpquailtyui/qms/dev-reviewer-home-page',
  'DEV-Closure': './rqpquailtyui/qms/dev-reviewer-home-page',
  'DEVA-Initiator': './rqpquailtyui/qms/deva-initiator',
  'DEVA-Update': './rqpquailtyui/qms/deva-update-home-page',
  'DEVA-Reviewer': './rqpquailtyui/qms/deva-reviewer-home-page',
  'DEVA-Approver': './rqpquailtyui/qms/deva-reviewer-home-page',
  'NCIA-Initiator': './rqpquailtyui/qms/ncia-initiator',
  'NCIA-Reviewer': './rqpquailtyui/qms/ncia-reviewer-home-page',
  'NCIA-Approver': './rqpquailtyui/qms/ncia-reviewer-home-page',
  'NCIA-Update': './rqpquailtyui/qms/ncia-update-home-page',
  'NCI-Initiator': './rqpquailtyui/qms/nci-initiator',
  'GWL-Initiator': './gl/gwl-initiator',
  'GWL-Reviewer': './gl/gwl-reviewer',
  'GWL-Approver': './gl/gwl-reviewer',
  'GWL-Update': './gl/gwl-update',
  'NCI-Department Reviewer':
    './rqpquailtyui/qms/nci-department-review-home-page',
  'NCI-Reviewer': './rqpquailtyui/qms/nci-qa-review-home-page',
  'NCI-Cross Functional Reviewer':
    './rqpquailtyui/qms/nci-cross-review-home-page',
  'NCI-Approver': './rqpquailtyui/qms/nci-qa-approver-review-home-page',
  'NCI-Authorization': './rqpquailtyui/qms/nci-authorization-review-home-page',
  'NCI-Closure': './rqpquailtyui/qms/nci-closure-review-home-page',
  'NCI-Update': './rqpquailtyui/qms/nci-update-home-page',
  'CC-Initiator': './rqpquailtyui/qms/cc-initiator',
  'CC-Update': './rqpquailtyui/qms/cc-update-home-page',
  'CC-Department Reviewer': './rqpquailtyui/qms/cc-reviewer-home-page',
  'CC-QA Reviewer': './rqpquailtyui/qms/cc-reviewer-home-page',
  'CC-Cross Functional Reviewer': './rqpquailtyui/qms/cc-reviewer-home-page',
  'CC-Approver': './rqpquailtyui/qms/cc-reviewer-home-page',
  'CC-QA Approver': './rqpquailtyui/qms/cc-reviewer-home-page',
  'CCA-Initiator': './rqpquailtyui/qms/cca-initiator',
  'CCA-Update': './rqpquailtyui/qms/cca-update-home-page',
  'CCA-Reviewer': './rqpquailtyui/qms/cca-reviewer-home-page',
  'CCA-Approver': './rqpquailtyui/qms/cca-reviewer-home-page',
  'CAPAA-Initiator': './rqpquailtyui/qms/capaa-initiator',
  'CAPAA-Update': './rqpquailtyui//qms/capaa-update-home-page',
  'CAPAA-Reviewer': './rqpquailtyui/qms/capaa-reviewer-home-page',
  'CAPAA-Approver': './rqpquailtyui/qms/capaa-reviewer-home-page',
  'MM-Master Data': '/rqpadminui/mm/mm-master-data-home-page',
  'PDQ-Initiator': './rqpadminui/mm/dq-initiator',
  'PDQ-Update': './rqpadminui/mm/dq-update',
  'PDQ-Reviewer': './rqpadminui/mm/dq-reviewer',
  'PDQ-Approver': './rqpadminui/mm/dq-reviewer',
  'FQ-Update': './rqpadminui/sd/fair-update-home-page',
  'PFQ-Initiator': './rqpadminui/mm/fq-initiator',
  'PFQ-Update': './rqpadminui/mm/fq-update',
  'PFQ-Reviewer': './rqpadminui/mm/fq-reviewer',
  'PFQ-Approver': './rqpadminui/mm/fq-reviewer',
  'PPO-Initiator': './rqpadminui/mm/po-initiator',
  'PPO-Update': './rqpadminui/mm/po-update',
  'PPO-Reviewer': './rqpadminui/mm/po-reviewer',
  'PPO-Approver': './rqpadminui/mm/po-reviewer',
  'PQT-Initiator': './rqpadminui/mm/qt-initiator',
  'PQT-Reviewer': './rqpadminui/mm/qt-reviewer',
  'PQT-Approver': './rqpadminui/mm/qt-reviewer',
  'PQT-Update': './rqpadminui/mm/qt-update',
  'PSI-Initiator': './rqpadminui/mm/si-initiator',
  'PSI-Reviewer': './rqpadminui/mm/si-reviewer',
  'PSI-Approver': './rqpadminui/mm/si-reviewer',
  'PSI-Update': './rqpadminui/mm/si-update',
  'PSO-Initiator': './rqpadminui/mm/so-initiator',
  'PSO-Reviewer': './rqpadminui/mm/so-reviewer',
  'PSO-Approver': './rqpadminui/mm/so-reviewer',
  'PSO-Update': './rqpadminui/mm/so-update',
  'PDO-Initiator': './rqpadminui/mm/do-initiator',
  'PDO-Reviewer': './rqpadminui/mm/do-reviewer',
  'PDO-Approver': './rqpadminui/mm/do-reviewer',
  'PDO-Update': './rqpadminui/mm/do-update',
  'SSI-Initiator': './rqpadminui/sd/si-initiator',
  'SSI-Update': './rqpadminui/sd/si-update',
  'SSI-Reviewer': './rqpadminui/sd/si-reviewer',
  'SSI-Approver': './rqpadminui/sd/si-reviewer',
  'SFQ-Initiator': './rqpadminui/sd/fair-init',
  'SFQ-Update': './rqpadminui/sd/fair-update',
  'SFQ-Reviewer': './rqpadminui/sd/fair-reviewer',
  'SFQ-Approver': './rqpadminui/sd/fair-reviewer',
  'SDQ-Initiator': './rqpadminui/sd/dq-init',
  'SDQ-Update': './rqpadminui/sd/dq-update',
  'SDQ-Reviewer': './rqpadminui/sd/dq-reviwer',
  'SDQ-Approver': './rqpadminui/sd/dq-reviwer',
  'SSO-Initiator': './rqpadminui/sd/so-initiator',
  'SSO-Reviewer': './rqpadminui/sd/so-reviewer',
  'SSO-Approver': './rqpadminui/sd/so-reviewer',
  'SSO-Update': './rqpadminui/sd/so-update',
  'SDO-Initiator': './rqpadminui/sd/do-initiator',
  'SDO-Reviewer': './rqpadminui/sd/do-reviewer',
  'SDO-Approver': './rqpadminui/sd/do-reviewer',
  'SDO-Update': './rqpadminui/sd/do-update',
  'SPO-Initiator': './rqpadminui/sd/po-initiator',
  'SPO-Update': './rqpadminui/sd/po-update',
  'SPO-Reviewer': './rqpadminui/sd/po-reviewer',
  'SPO-Approver': './rqpadminui/sd/po-reviewer',
  'URS-Module Admin': './dms/dms-module-admin',
  'LMSQB-Update': './rqpquailtyui/lms/lmsqb-update-home-page',
  'LMSQB-Initiator': './rqpquailtyui/lms/lmsqb-initator',
  'LMSQB-Approver': './rqpquailtyui/lms/lmsqb-reviewer',
  'LIT-Initiator': './rqpquailtyui/lms/lit-initiator',
  'TQ-Initiator': './rqpquailtyui/lms/tq-initiator',
  'TQ-Update': './rqpquailtyui/lms/tq-update',
  'TQ-Department Reviewer': './rqpquailtyui/lms/tq-review-home-page',
  'TQ-Department Head': './rqpquailtyui/lms/tq-department-head',
  'TQ-QA Approver': './rqpquailtyui/lms/tq-approver',
  'LIT-Update': './rqpquailtyui/lms/lit-update-home-page',
  'LIT-Department Reviewer': './rqpquailtyui/lms/lit-department-home-page',
  'LIT-Department Head': './rqpquailtyui/lms/lit-department-head-home-page',
  'LIT-QA Approver': './rqpquailtyui/lms/lit-approver',
  'URS-PR-Initiator': './dms/urs-pr-init-save',
  'URS-PR-Update': './dms/urs-pr-update',
  'URS-PR-Reviewer': './dms/urs-pr-reviewer',
  'URS-PR-Approver': './dms/urs-pr-reviewer',
  'URS-PR-Print': './dms/urs-pr-reviewer',
  'ES-Initiator': './excel/es-init',
  'ES-Update': './excel/es-update',
  'ES-Reviewer': './excel/es-reviewer',
  'ES-Approver': './excel/es-reviewer',
  'RAS1-Initiator': './rqpquailtyui/excel/rasi-init',
  'RAS1-Update': './rqpquailtyui/excel/rasi-update',
  'RAS1-Reviewer': './rqpquailtyui/excel/rasi-reviewer',
  'RAS1-Approver': './rqpquailtyui/excel/rasi-reviewer',
  'RAS2-Initiator': '/excel/ras2-init',
  'RAS2-Update': '/excel/ras2-update',
  'RAS2-Reviewer': '/excel/ras2-reviewer',
  'RAS2-Approver': '/excel/ras2-reviewer',
  'WSR-Initiator': '/lims/wsr-init',
  'WSR-Update': '/lims/wsr-update',
  'WSR-Reviewer': '/lims/wsr-reviewer',
  'WSR-Approver': '/lims/wsr-reviewer',
  'FAS1-Initiator': './rqpquailtyui/excel/fas1-initiator',
  'BLG-Initiator': '/blg/blg-initiator',
  'BLG-Update': '/blg/blg-update',
  'BLG-Reviewer': '/blg/blg-reviewer',
  'BLG-Approver': '/blg/blg-reviewer',
  'FAS1-Update': './rqpquailtyui/excel/fas1-update',
  'FAS1-Reviewer': './rqpquailtyui/excel/fas1-reviewer',
  'FAS1-Approver': './rqpquailtyui/excel/fas1-reviewer',
  'TR-Initiator': '/lims/test-registration-initiator',
  'TR-Update': '/lims/test-registration-update',
  'TR-Reviewer': '/lims/test-registration-reviewer',
  'TR-Approver': '/lims/test-registration-reviewer',
  'UPM-Master Data': './rqpadminui/admin/upr-master-data',
  'LCM-Master Data': './rqpadminui/admin/lcm-master-data',
  'PLD-Initiator': '/clv/pld-init',
  'PLD-Update': '/clv/pld-update',
  'PLD-Approver': '/clv/pld-approver',
  'MRSLE-Initiator': './rqpquailtyui/excel/mrsle-init',
  'MRSLE-Update': './rqpquailtyui/excel/mrsle-update',
  'MRSLE-Reviewer': './rqpquailtyui/excel/mrsle-reviewer',
  'MRSLE-Approver': './rqpquailtyui/excel/mrsle-reviewer',
  'Blog-Management': './blg/blog-master-home-page',
  'MRSSST-Initiator': '/excel/mrssst-init',
  'MRSSST-Update': '/excel/mrssst-update',
  'MRSSST-Reviewer': '/excel/mrssst-reviewer',
  'MRSSST-Approver': '/excel/mrssst-reviewer',
  'MRSFD-Initiator': '/excel/mrsfd-init',
  'MRSFD-Update': '/excel/mrsfd-update',
  'MRSFD-Reviewer': '/excel/mrsfd-reviewer',
  'MRSFD-Approver': '/excel/mrsfd-reviewer',
  'MRSSS-Initiator': '/excel/mrsss-init',
  'MRSSS-Update': '/excel/mrsss-update',
  'MRSSS-Reviewer': '/excel/mrsss-reviewer',
  'MRSSS-Approver': '/excel/mrsss-reviewer',
  'MRSMP-Initiator': '/excel/mrsmp-init',
  'MRSMP-Update': '/excel/mrsmp-update',
  'MRSMP-Reviewer': '/excel/mrsmp-reviewer',
  'MRSMP-Approver': '/excel/mrsmp-reviewer',
  'MRSA-Initiator': '/excel/mrsa-init',
  'MRSA-Update': '/excel/mrsa-update',
  'MRSA-Reviewer': '/excel/mrsa-reviewer',
  'MRSA-Approver': '/excel/mrsa-reviewer',
  'TPC-Initiator': './rqpquailtyui/lims/topic-registration-init',
  'TPC-Update': '/lims/topic-registration-update',
  'TPC-Reviewer': '/lims/topic-registration-reviewer',
  'TPC-Approver': '/lims/topic-registration-reviewer',
  'TH-Initiator': '/lims/training-schedule-initiator',
  'TH-Update': '/lims/training-schedule-update',
  'TH-Approver': '/lims/training-schedule-reviewer',
  'CS-Approver': '/lims/course-session-reviewer',
  'CS-Update': './rqpquailtyui/lims/course-session-update',
  'CS-Initiator': './rqpquailtyui/lims/course-session-initiator',
  'CRS-Initiator': './rqpquailtyui/lims/course-initiator',
  'CRS-Update': './rqpquailtyui/lims/course-update',
  'CRS-Approver': './rqpquailtyui/lims/course-reviewer',
  'GTP-Initiator': '/lims/gtp-init',
  'GTP-Update': '/lims/gtp-update',
  'GTP-Reviewer': 'lims/gtp-reviewer',
  'GTP-Approver': 'lims/gtp-reviewer',
  'SPM-Initiator': './rmp/spm-master-home-page',
  'SPM-Update': './rmp/spm-master-home-page',
  'SPM-Approver': './rmp/spm-master-home-page',
};
