import { Pipe, PipeTransform } from '@angular/core';

@Pipe({
    name: 'backgroundColor',
    standalone: false
})
export class BackgroundColorPipe implements PipeTransform {
  transform(
    value: unknown,
    labelName: string,
    highLight?: boolean,
    isSectionName?: boolean,
    isDepartmentName?: boolean,
    isRiskRating?: boolean,
    isLineCode?: boolean,
    isSectionCode?: boolean,
    isDepartmentCode?: boolean,
    isCleaningCategory?: boolean,
    isProductCleanDataNo?: boolean,
    isProductName?: boolean,
    isProductCode?: boolean,
    isToxicity?: boolean,
    isOralLD50?: boolean,
    isConcentration?: boolean,
    isPotency?: boolean,
    isEquipmentName?: boolean,
    isSurfaceArea?: boolean,
    isPurpose?: boolean,
    isSection?: boolean,
    isDepartment?: boolean,
    isLineNo?: boolean,
    isProductContact?: boolean,
    isParts?: boolean,
    isSolubilityDefinition?: boolean,
    isOrganizationUnitCode?: boolean,
    isModuleCode?: boolean,
    isActionTypeNumber?: boolean,
    isActionTypeCode?: boolean,
    isClassificationName?: boolean,
    isClassificationCode?: boolean,
    isItemSubCategoryName?: boolean,
    isItemSubCategoryCode?: boolean,
    isCategoryCode?: boolean,
    isParameter?: boolean,
    isParameterName?: boolean,
    isParameterCode?: boolean,
    isParameterScore?: boolean,
    isRootCourseType?: boolean,
    isRootCourseCode?: boolean,
    isImageName?: boolean,
    isImageType?: boolean,
    isCategory?: boolean,
    isScrollText?: boolean,
    isDocumentTypeCode?: boolean,
    isDocumentTypeName?: boolean,
    isBusinessUnitCode?: boolean,
    isBusinessUnitTypeCode?: boolean,
    isOrganizationName?: boolean,
    isDesignationName?: boolean,
    isDesignationCode?: boolean,
    isMaterialSubTypeName?: boolean,
    isMaterialSubTypeCode?: boolean,
    isMaterialTypeName?: boolean,
    isMaterialTypeCode?: boolean,
    isModuleName?: boolean,
    isModuleType?: boolean,
    isOrganizationCode?: boolean,
    isPackName?: boolean,
    isPaymentTermsCode?: boolean,
    isPaymentTermsDescription?: boolean,
    isStandardReasonCode?: boolean,
    isTaxName?: boolean,
    isTaxCode?: boolean,
    isRoleName?: boolean,
    isPlantCode?: boolean,
    isSecurityProfileCode?: boolean,
    isBranchCode?: boolean,
    isLoginInTime?: boolean,
    isPasswordMessage?: boolean
  ): string {
    if (
      this.checkCondition(
        labelName,
        highLight,
        isSectionName,
        isDepartmentName,
        isRiskRating,
        isLineCode,
        isSectionCode,
        isDepartmentCode,
        isCleaningCategory,
        isProductCleanDataNo,
        isProductName,
        isProductCode,
        isToxicity,
        isOralLD50,
        isConcentration,
        isPotency,
        isEquipmentName,
        isSurfaceArea,
        isPurpose,
        isSection,
        isDepartment,
        isLineNo,
        isProductContact,
        isParts,
        isSolubilityDefinition,
        isOrganizationUnitCode,
        isModuleCode,
        isActionTypeNumber,
        isActionTypeCode,
        isClassificationName,
        isClassificationCode,
        isItemSubCategoryName,
        isItemSubCategoryCode,
        isCategoryCode,
        isParameter,
        isParameterCode,
        isParameterScore,
        isParameterName,
        isRootCourseType,
        isRootCourseCode,
        isImageName,
        isImageType,
        isCategory,
        isScrollText,
        isDocumentTypeCode,
        isDocumentTypeName,
        isBusinessUnitCode,
        isBusinessUnitTypeCode,
        isOrganizationName,
        isDesignationName,
        isDesignationCode,
        isMaterialSubTypeName,
        isMaterialSubTypeCode,
        isMaterialTypeName,
        isMaterialTypeCode,
        isModuleName,
        isModuleType,
        isOrganizationCode,
        isPackName,
        isPaymentTermsCode,
        isPaymentTermsDescription,
        isStandardReasonCode,
        isTaxName,
        isTaxCode,
        isRoleName,
        isPlantCode,
        isSecurityProfileCode,
        isBranchCode,
        isLoginInTime,
        isPasswordMessage
      )
    ) {
      return 'red';
    }
    return 'none';
  }

  private checkCondition(
    labelName: string,
    isLineName?: boolean,
    isSectionName?: boolean,
    isDepartmentName?: boolean,
    isRiskRating?: boolean,
    isLineCode?: boolean,
    isSectionCode?: boolean,
    isDepartmentCode?: boolean,
    isCleaningCategory?: boolean,
    isProductCleanDataNo?: boolean,
    isProductName?: boolean,
    isProductCode?: boolean,
    isToxicity?: boolean,
    isOralLD50?: boolean,
    isConcentration?: boolean,
    isPotency?: boolean,
    isEquipmentName?: boolean,
    isSurfaceArea?: boolean,
    isPurpose?: boolean,
    isSection?: boolean,
    isDepartment?: boolean,
    isLineNo?: boolean,
    isProductContact?: boolean,
    isParts?: boolean,
    isSolubilityDefinition?: boolean,
    isOrganizationUnitCode?: boolean,
    isModuleCode?: boolean,
    isActionTypeNumber?: boolean,
    isActionTypeCode?: boolean,
    isClassificationName?: boolean,
    isClassificationCode?: boolean,
    isItemSubCategoryName?: boolean,
    isItemSubCategoryCode?: boolean,
    isCategoryCode?: boolean,
    isParameter?: boolean,
    isParameterName?: boolean,
    isParameterCode?: boolean,
    isParameterScore?: boolean,
    isRootCourseType?: boolean,
    isRootCourseCode?: boolean,
    isImageName?: boolean,
    isImageType?: boolean,
    isCategory?: boolean,
    isScrollText?: boolean,
    isDocumentTypeCode?: boolean,
    isDocumentTypeName?: boolean,
    isBusinessUnitCode?: boolean,
    isBusinessUnitTypeCode?: boolean,
    isOrganizationName?: boolean,
    isDesignationName?: boolean,
    isDesignationCode?: boolean,
    isMaterialSubTypeName?: boolean,
    isMaterialSubTypeCode?: boolean,
    isMaterialTypeName?: boolean,
    isMaterialTypeCode?: boolean,
    isModuleName?: boolean,
    isModuleType?: boolean,
    isOrganizationCode?: boolean,
    isPackName?: boolean,
    isPaymentTermsCode?: boolean,
    isPaymentTermsDescription?: boolean,
    isStandardReasonCode?: boolean,
    isTaxName?: boolean,
    isTaxCode?: boolean,
    isRoleName?: boolean,
    isPlantCode?: boolean,
    isSecurityProfileCode?: boolean,
    isBranchCode?: boolean,
    isLoginInTime?: boolean,
    isPasswordMessage?: boolean
  ): boolean {
    const data = {
      'Line Name': isLineName,
      'Section Name': isSectionName,
      'Department Name': isDepartmentName,
      'Risk Rating': isRiskRating,
      'Line Code': isLineCode,
      'Section Code': isSectionCode,
      'Department Code': isDepartmentCode,
      'Cleaning Category': isCleaningCategory,
      'Product Clean Data No': isProductCleanDataNo,
      'Product Name': isProductName,
      'Product Code': isProductCode,
      Toxicity: isToxicity,
      'Oral LD50(single dose to rats), mg/kg': isOralLD50,
      'Concentration, mg/kg': isConcentration,
      Potency: isPotency,
      'Equipment Name': isEquipmentName,
      Section: isSection,
      'Line No': isLineNo,
      'Surface Area': isSurfaceArea,
      'Product Contact': isProductContact,
      Purpose: isPurpose,
      Department: isDepartment,
      'Parts of Water Required for 1 Part of Solute': isParts,
      'Solubility Definition': isSolubilityDefinition,
      'Organization Unit Code': isOrganizationUnitCode,
      'Module Code': isModuleCode,
      'Action Type Number': isActionTypeNumber,
      'Action Type Code': isActionTypeCode,
      'Classification Name': isClassificationName,
      'Classification Code': isClassificationCode,
      'Item Sub Category Name': isItemSubCategoryName,
      'Item Sub Category Code': isItemSubCategoryCode,
      'Category Code': isCategoryCode,
      Parameter: isParameter,
      'Parameter Code': isParameterName,
      'Parameter Score': isParameterCode,
      'Parameter Name': isParameterScore,
      'Root Course Type': isRootCourseType,
      'Root Course Code': isRootCourseCode,
      'Image Type': isImageType,
      'Image Name': isImageName,
      Category: isCategory,
      'Scroll Text': isScrollText,
      'Document Type Code': isDocumentTypeCode,
      'Document Type Name': isDocumentTypeName,
      'Business Unit Type Code': isBusinessUnitCode,
      'Business Unit Code': isBusinessUnitTypeCode,
      'Organization Name': isOrganizationName,
      'Designation Name': isDesignationName,
      'Designation Code': isDesignationCode,
      'Material Sub Type Name': isMaterialSubTypeName,
      'Material Sub Type Code': isMaterialSubTypeCode,
      'Material Type Name': isMaterialTypeName,
      'Material Type Code': isMaterialTypeCode,
      'Module Name': isModuleName,
      'Module Type': isModuleType,
      'Organization Code': isOrganizationCode,
      'Pack Name': isPackName,
      'Payment Terms Code': isPaymentTermsCode,
      'Payment Terms Description': isPaymentTermsDescription,
      'Standard Reason Code': isStandardReasonCode,
      'Tax Name': isTaxName,
      'Tax Code': isTaxCode,
      'Role Name': isRoleName,
      'Plant Code': isPlantCode,
      'Security Profile Code': isSecurityProfileCode,
      'Branch Code': isBranchCode,
      'Login In Time': isLoginInTime,
      'Password Message': isPasswordMessage,
    };
    return data[labelName] || false;
  }
}
